# Capsule Monster Chess uses Axmol as a focused 3D/glTF client runtime.
# Keep this list authoritative so cached native and Web builds cannot silently
# re-enable optional engine modules.

option(CMC_ENABLE_AUDIO "Build the client audio module" OFF)

set(_CMC_AXMOL_ENABLED_FEATURES
  AX_ENABLE_3D
  AX_ENABLE_GLTF
  AX_ENABLE_HTTP
  AX_ENABLE_WEBSOCKET
  AX_WITH_CURL
  AX_WITH_LLHTTP
  AX_WITH_WEBSOCKET_PARSER
  AX_WITH_UNZIP
  AX_WITH_CLIPPER2
  AX_WITH_POLY2TRI
  # Axmol's core Image object still references the ASTC decoder even when
  # legacy format detection is disabled. Keep its link dependency until that
  # engine source boundary is separated.
  AX_WITH_ASTCENC
  AX_CORE_PROFILE
)

set(_CMC_AXMOL_DISABLED_FEATURES
  AX_ENABLE_PHYSICS_2D
  AX_ENABLE_PHYSICS_3D
  AX_ENABLE_NAVMESH
  AX_ENABLE_LEGACY_3D
  AX_ENABLE_LEGACY_IMAGE_FORMATS
  AX_ENABLE_VIDEO
  AX_ENABLE_MFMEDIA
  AX_ENABLE_VLC_MEDIA
  AX_ENABLE_MSEDGE_WEBVIEW2
  AX_ENABLE_AUDIO
  AX_ENABLE_OPUS
  AX_ENABLE_VR
  AX_ENABLE_OPENXR
  AX_USE_BMP
  AX_USE_JPEG
  AX_USE_WEBP
  AX_WITH_JPEG
  AX_WITH_WEBP
  AX_WITH_FASTLZ
  AX_WITH_DOCTEST
  AX_EXT_HINT
  AX_ENABLE_EXT_LUA
  AX_ENABLE_EXT_GUI
  AX_ENABLE_EXT_ASSETMANAGER
  AX_ENABLE_EXT_SPINE
  AX_ENABLE_EXT_DRAGONBONES
  AX_ENABLE_EXT_SCENEIO
  AX_ENABLE_EXT_SCENEEXT
  AX_ENABLE_EXT_FAIRYGUI
  AX_ENABLE_EXT_IMGUI
  AX_ENABLE_EXT_LIVE2D
  AX_ENABLE_EXT_EFFEKSEER
  AX_ENABLE_EXT_PARTICLE3D
  AX_ENABLE_EXT_PHYSICS_NODE
  AX_ENABLE_EXT_INSPECTOR
  AX_ENABLE_EXT_SDFGEN
  AX_ENABLE_EXT_JSONDEFAULT
)

foreach(_cmc_feature IN LISTS _CMC_AXMOL_ENABLED_FEATURES)
  set(${_cmc_feature} ON CACHE BOOL "Required by Capsule Monster Chess" FORCE)
endforeach()

foreach(_cmc_feature IN LISTS _CMC_AXMOL_DISABLED_FEATURES)
  set(${_cmc_feature} OFF CACHE BOOL "Not used by Capsule Monster Chess" FORCE)
endforeach()

set(AX_ENABLE_AUDIO ${CMC_ENABLE_AUDIO} CACHE BOOL "Build the client audio module" FORCE)

unset(_cmc_feature)
unset(_CMC_AXMOL_ENABLED_FEATURES)
unset(_CMC_AXMOL_DISABLED_FEATURES)
